<?xml version="1.0"?>

  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_length" value="0.6"/>
  <xacro:property name="base_height" value="0.1"/>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <!-- Front Left wheel -->
  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 ${base_width/2} 0" rpy="1.5708 0 0"/>
    </visual>
  </link>

  <!-- Front Right wheel -->
  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 -${base_width/2} 0" rpy="1.5708 0 0"/>
    </visual>
  </link>

  <!-- Back Left Wheel-->
  <link name="back_left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 ${base_width/2} 0" rpy="1.5708 0 0"/>
    </visual>
  </link>

  <!-- Back Right wheel -->
  <link name="back_right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 -${base_width/2} 0" rpy="1.5708 0 0"/>
    </visual>
  </link>

  <!-- Joints -->
  <joint name"front_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin xyz="0 ${base_width/2} 0"/ rpy="0 0 0">
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin xyz="0 -${base_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name"back_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="back_left_wheel"/>
    <origin xyz="0 ${base_width/2} 0"/ rpy="0 0 0">
    <axis xyz="0 0 1"/>
  </joint>

  <joint name"back_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="back_right_wheel"/>
    <origin xyz="0 ${base_width/2} 0"/ rpy="0 0 0">
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Depth Camera -->
  <link name="depth_camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <origin xyz="0.1 0 0.1"/>
    </visual>
  </link> 
